#!/usr/bin/env bash
set -eu

git_branch=$(git symbolic-ref --short HEAD)

echo Assuming branch="${git_branch}"
for i in $(git remote)
do
 echo "-------[$i] git pull"
 git pull "${i}" "${git_branch}"
done
for i in $(git remote)
do
  echo "-------[$i] git push"
  git push "${i}" "${git_branch}"
done

