#!/usr/bin/env bash
set -eu

usage() {
  printf 'usage: git dependabot-merge [-r <remote>]
OPTIONS
  -f  Set the additional filter (example: github_actions) [default: ""]
  -r  Set the remote to check [default: origin]

EXAMPLES
git dependabot-merge -r github
git dependabot-merge
'
}

filter=""
remote="origin"
help=false

while getopts :r:f:h flag
do
  case "${flag}" in
    f) filter=${OPTARG};;
    r) remote=${OPTARG};;
    h) help=true;;
    *)
  esac
done

if [ "$help" = true ]; then
  usage
  exit 1
fi

default_branch=$(git remote show "${remote}" | grep 'HEAD branch' | cut -d' ' -f5)

git fetch "$remote"
git remote prune "$remote"
git branch -f dependabot-merge "${default_branch}"

git for-each-ref --shell --format="ref=%(refname)" "refs/remotes/${remote}/dependabot/${filter}" | \
while read -r entry
do
  eval "${entry}"
  ref="${ref:?}"
  branch="${ref#refs/remotes/"${remote}"/}"
  echo "Working on ${branch}"
  git checkout "${branch}"
  git rebase dependabot-merge
  git checkout dependabot-merge
  git merge --ff-only "${branch}"
done
